#line 2 "parser/lexer.cpp"

#line 4 "parser/lexer.cpp"

#define YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

/* %not-for-header */
/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */
/* %ok-for-header */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* %if-c++-only */
/* The c++ scanner is a mess. The FlexLexer.h header file relies on the
 * following macro. This is required in order to pass the c++-multiple-scanners
 * test in the regression suite. We get reports that it breaks inheritance.
 * We will address this in a future release of flex, or omit the C++ scanner
 * altogether.
 */
#define yyFlexLexer Yacc_FlexLexer
/* %endif */

/* %if-c-only */
/* %endif */

#ifdef yyalloc
#define Yacc_alloc_ALREADY_DEFINED
#else
#define yyalloc Yacc_alloc
#endif

#ifdef yyrealloc
#define Yacc_realloc_ALREADY_DEFINED
#else
#define yyrealloc Yacc_realloc
#endif

#ifdef yyfree
#define Yacc_free_ALREADY_DEFINED
#else
#define yyfree Yacc_free
#endif

/* %if-c-only */
/* %endif */

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
/* %if-c-only */
/* %endif */

/* %if-tables-serialization */
/* %endif */
/* end standard C headers. */

/* %if-c-or-c++ */
/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined(__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types.
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t   flex_int8_t;
typedef uint8_t  flex_uint8_t;
typedef int16_t  flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t  flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char        flex_int8_t;
typedef short int          flex_int16_t;
typedef int                flex_int32_t;
typedef unsigned char      flex_uint8_t;
typedef unsigned short int flex_uint16_t;
typedef unsigned int       flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN (-32767 - 1)
#endif
#ifndef INT32_MIN
#define INT32_MIN (-2147483647 - 1)
#endif
#ifndef INT8_MAX
#define INT8_MAX (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* %endif */

/* begin standard C++ headers. */
/* %if-c++-only */
#include <iostream>
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */
/* %endif */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* %not-for-header */
/* Returned upon end-of-file. */
#define YY_NULL 0
/* %ok-for-header */

/* %not-for-header */
/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR)(c))
/* %ok-for-header */

/* %if-reentrant */
/* %endif */

/* %if-not-reentrant */

/* %endif */

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin)
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state* YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

/* %if-not-reentrant */
extern int yyleng;
/* %endif */

/* %if-c-only */
/* %if-not-reentrant */
/* %endif */
/* %endif */

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

#define YY_LESS_LINENO(n)
#define YY_LINENO_REWIND_TO(ptr)

/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n)                                                                               \
    do {                                                                                        \
        /* Undo effects of setting up yytext. */                                                \
        int yyless_macro_arg = (n);                                                             \
        YY_LESS_LINENO(yyless_macro_arg);                                                       \
        *yy_cp                                = (yy_hold_char);                                 \
        YY_RESTORE_YY_MORE_OFFSET(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
        YY_DO_BEFORE_ACTION; /* set up yytext again */                                          \
    } while (0)
#define unput(c) yyunput(c, (yytext_ptr))

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
{
    /* %if-c-only */
    /* %endif */

    /* %if-c++-only */
    std::streambuf* yy_input_file;
    /* %endif */

    char* yy_ch_buf;  /* input buffer */
    char* yy_buf_pos; /* current position in input buffer */

    /* Size of input buffer in bytes, not including room for EOB
     * characters.
     */
    int yy_buf_size;

    /* Number of characters read into yy_ch_buf, not including EOB
     * characters.
     */
    int yy_n_chars;

    /* Whether we "own" the buffer - i.e., we know we created it,
     * and can realloc() it to grow it, and should free() it to
     * delete it.
     */
    int yy_is_our_buffer;

    /* Whether this is an "interactive" input source; if so, and
     * if we're using stdio for input, then we want to use getc()
     * instead of fread(), to make sure we stop fetching input after
     * each newline.
     */
    int yy_is_interactive;

    /* Whether we're considered to be at the beginning of a line.
     * If so, '^' rules will be active on the next match, otherwise
     * not.
     */
    int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

    /* Whether to try to fill the input buffer when we reach the
     * end of it.
     */
    int yy_fill_buffer;

    int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
    /* When an EOF's been seen but there's still some text to process
     * then we mark the buffer as YY_EOF_PENDING, to indicate that we
     * shouldn't try reading from the input source any more.  We might
     * still have a bunch of tokens to match, though, because of
     * possible backing-up.
     *
     * When we actually see the EOF, we change the status to "new"
     * (via yyrestart()), so that the user can continue scanning by
     * just pointing yyin at a new input file.
     */
#define YY_BUFFER_EOF_PENDING 2
};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %if-not-reentrant */
/* %endif */
/* %ok-for-header */

/* %endif */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ((yy_buffer_stack) ? (yy_buffer_stack)[(yy_buffer_stack_top)] : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* %if-c-only Standard (non-C++) definition */
/* %if-not-reentrant */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
/* %endif */

void* yyalloc(yy_size_t);
void* yyrealloc(void*, yy_size_t);
void  yyfree(void*);

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive)                                  \
    {                                                                       \
        if (!YY_CURRENT_BUFFER)                                             \
        {                                                                   \
            yyensure_buffer_stack();                                        \
            YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE); \
        }                                                                   \
        YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive;       \
    }
#define yy_set_bol(at_bol)                                                  \
    {                                                                       \
        if (!YY_CURRENT_BUFFER)                                             \
        {                                                                   \
            yyensure_buffer_stack();                                        \
            YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE); \
        }                                                                   \
        YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol;                       \
    }
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* %% [1.0] yytext/yyin/yyout/yy_state_type/yylineno etc. def's & init go here */
/* Begin user sect3 */
#define YY_SKIP_YYWRAP

#define FLEX_DEBUG
typedef flex_uint8_t YY_CHAR;

#define yytext_ptr yytext
#define YY_INTERACTIVE

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
{
    LexerError("yyFlexLexer::yylex invoked but %option yyclass used");
    return 0;
}

#define YY_DECL int Scanner::yylex()

/* %% [1.5] DFA */

/* %if-c-only Standard (non-C++) definition */
/* %endif */

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION                                                   \
    (yytext_ptr) = yy_bp;                                                     \
    /* %% [2.0] code to fiddle yytext and yyleng for yymore() goes here \ */  \
    yyleng         = (int)(yy_cp - yy_bp);                                    \
    (yy_hold_char) = *yy_cp;                                                  \
    *yy_cp         = '\0';                                                    \
    /* %% [3.0] code to copy yytext_ptr to yytext[] goes here, if %array \ */ \
    (yy_c_buf_p) = yy_cp;
/* %% [4.0] data tables for the DFA and the user's section 1 definitions go here */
#define YY_NUM_RULES 58
#define YY_END_OF_BUFFER 59
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
{
    flex_int32_t yy_verify;
    flex_int32_t yy_nxt;
};
static const flex_int16_t yy_accept[133] = {0,
    0,
    0,
    59,
    58,
    3,
    1,
    2,
    22,
    58,
    31,
    24,
    52,
    53,
    29,
    27,
    20,
    28,
    32,
    30,
    50,
    51,
    19,
    26,
    21,
    25,
    43,
    54,
    55,
    43,
    43,
    43,
    43,
    43,
    43,
    43,
    43,
    43,
    43,
    43,
    56,
    23,
    57,
    2,
    36,
    0,
    44,
    37,
    42,
    45,
    0,
    41,
    39,
    45,
    50,
    0,
    0,
    49,
    51,
    34,
    35,
    33,
    43,
    43,
    43,
    43,
    43,
    16,
    43,
    43,
    43,
    43,
    7,
    43,
    43,
    43,
    43,
    43,
    38,
    0,
    45,
    0,
    0,
    39,
    0,
    46,
    47,
    49,
    43,
    43,
    43,
    43,
    43,
    9,
    43,
    4,
    43,
    43,
    43,
    43,
    40,

    47,
    0,
    49,
    0,
    43,
    14,
    43,
    43,
    8,
    43,
    15,
    43,
    43,
    6,
    43,
    0,
    47,
    0,
    48,
    12,
    18,
    43,
    5,
    43,
    43,
    10,
    43,
    17,
    13,
    43,
    11,
    0};

static const YY_CHAR yy_ec[256] = {0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    2,
    3,
    4,
    4,
    4,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    4,
    5,
    6,
    1,
    1,
    7,
    8,
    1,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    18,
    18,
    18,
    18,
    18,
    18,
    19,
    19,
    1,
    20,
    21,
    22,
    23,
    1,
    1,
    24,
    24,
    24,
    24,
    25,
    24,
    26,
    26,
    26,
    26,
    26,
    26,
    26,
    26,
    26,
    27,
    26,
    26,
    26,
    26,
    26,
    26,
    26,
    28,
    26,
    26,
    29,
    1,
    30,
    1,
    26,
    1,
    31,
    32,
    33,
    34,

    35,
    36,
    37,
    38,
    39,
    26,
    40,
    41,
    26,
    42,
    43,
    27,
    26,
    44,
    45,
    46,
    47,
    48,
    49,
    28,
    26,
    26,
    50,
    51,
    52,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,

    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1};

static const YY_CHAR yy_meta[53] = {0,
    1,
    1,
    2,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    3,
    1,
    3,
    4,
    1,
    5,
    5,
    5,
    1,
    1,
    1,
    1,
    5,
    5,
    6,
    7,
    6,
    1,
    1,
    5,
    5,
    5,
    5,
    5,
    5,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    6,
    1,
    1,
    1};

static const flex_int16_t yy_base[143] = {0,
    0,
    0,
    232,
    461,
    461,
    461,
    197,
    175,
    187,
    461,
    180,
    461,
    461,
    171,
    461,
    461,
    461,
    36,
    46,
    41,
    55,
    461,
    149,
    146,
    139,
    46,
    461,
    461,
    60,
    64,
    67,
    70,
    74,
    79,
    82,
    95,
    102,
    109,
    115,
    461,
    92,
    461,
    121,
    461,
    110,
    461,
    461,
    461,
    119,
    128,
    98,
    0,
    131,
    140,
    145,
    155,
    93,
    164,
    461,
    461,
    461,
    0,
    159,
    167,
    173,
    177,
    186,
    189,
    192,
    195,
    198,
    203,
    206,
    209,
    212,
    219,
    223,
    461,
    228,
    231,
    91,
    59,
    0,
    242,
    246,
    41,
    79,
    249,
    252,
    255,
    258,
    264,
    267,
    271,
    279,
    285,
    288,
    291,
    294,
    461,

    40,
    91,
    108,
    117,
    298,
    301,
    304,
    309,
    312,
    322,
    325,
    328,
    334,
    337,
    340,
    127,
    186,
    242,
    280,
    343,
    346,
    352,
    359,
    362,
    365,
    368,
    371,
    374,
    378,
    381,
    388,
    461,
    418,
    421,
    428,
    435,
    439,
    440,
    443,
    447,
    452,
    455};

static const flex_int16_t yy_def[143] = {0,
    132,
    1,
    132,
    132,
    132,
    132,
    132,
    132,
    133,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    134,
    132,
    132,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    132,
    132,
    132,
    132,
    132,
    133,
    132,
    132,
    132,
    132,
    132,
    135,
    136,
    132,
    132,
    132,
    132,
    137,
    132,
    132,
    132,
    132,
    138,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    132,
    132,
    132,
    135,
    135,
    136,
    132,
    132,
    139,
    140,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    132,

    139,
    141,
    140,
    142,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    141,
    141,
    142,
    142,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    134,
    0,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132};

static const flex_int16_t yy_nxt[514] = {0,
    4,
    5,
    6,
    7,
    8,
    9,
    10,
    11,
    12,
    13,
    14,
    15,
    16,
    17,
    18,
    19,
    20,
    21,
    21,
    22,
    23,
    24,
    25,
    26,
    26,
    26,
    26,
    26,
    27,
    28,
    26,
    29,
    30,
    31,
    32,
    33,
    34,
    26,
    35,
    26,
    26,
    26,
    26,
    36,
    37,
    26,
    26,
    38,
    39,
    40,
    41,
    42,
    49,
    49,
    49,
    53,
    51,
    54,
    54,
    55,
    50,
    52,
    62,
    62,
    62,
    56,
    102,
    102,
    57,
    53,
    50,
    58,
    58,
    58,
    100,
    56,
    62,
    62,
    62,
    56,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    56,
    62,
    62,
    62,
    86,
    65,
    62,
    62,
    62,
    62,
    62,

    62,
    82,
    116,
    64,
    116,
    104,
    66,
    86,
    82,
    67,
    68,
    62,
    62,
    62,
    69,
    46,
    70,
    72,
    62,
    62,
    62,
    71,
    86,
    73,
    43,
    62,
    62,
    62,
    118,
    74,
    118,
    62,
    62,
    62,
    132,
    49,
    49,
    49,
    132,
    79,
    132,
    79,
    78,
    50,
    80,
    80,
    80,
    49,
    49,
    49,
    75,
    76,
    77,
    50,
    53,
    50,
    54,
    54,
    55,
    53,
    61,
    55,
    55,
    55,
    56,
    50,
    84,
    60,
    84,
    56,
    59,
    85,
    85,
    85,
    56,
    62,
    62,
    62,
    53,
    56,
    58,
    58,
    58,
    62,
    62,
    62,
    48,
    47,
    56,
    62,
    62,
    62,
    46,
    62,
    62,
    62,
    44,
    132,
    56,
    132,

    43,
    88,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    89,
    90,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    132,
    132,
    91,
    92,
    62,
    62,
    62,
    93,
    62,
    62,
    62,
    132,
    94,
    80,
    80,
    80,
    80,
    80,
    80,
    97,
    95,
    132,
    132,
    96,
    132,
    132,
    98,
    85,
    85,
    85,
    99,
    85,
    85,
    85,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    132,
    132,
    105,
    62,
    62,
    62,
    62,
    62,
    62,
    106,
    62,
    62,
    62,
    132,
    132,
    109,
    132,
    110,
    62,
    62,
    62,
    132,
    107,

    108,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    111,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    132,
    114,
    62,
    62,
    62,
    62,
    62,
    62,
    112,
    132,
    113,
    115,
    132,
    132,
    120,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    122,
    132,
    121,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    132,
    125,
    123,
    62,
    62,
    62,
    124,
    132,
    132,
    126,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    62,
    127,
    62,
    62,
    62,
    62,
    62,
    62,

    132,
    132,
    129,
    128,
    62,
    62,
    62,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    131,
    132,
    130,
    45,
    45,
    45,
    45,
    45,
    45,
    45,
    63,
    63,
    63,
    81,
    81,
    81,
    81,
    81,
    81,
    81,
    83,
    132,
    83,
    83,
    83,
    83,
    83,
    87,
    87,
    62,
    62,
    62,
    101,
    132,
    101,
    103,
    103,
    132,
    103,
    117,
    132,
    117,
    119,
    132,
    119,
    3,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,

    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132};

static const flex_int16_t yy_chk[514] = {0,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    1,
    18,
    18,
    18,
    20,
    19,
    20,
    20,
    20,
    18,
    19,
    26,
    26,
    26,
    20,
    101,
    86,
    20,
    21,
    18,
    21,
    21,
    21,
    82,
    20,
    29,
    29,
    29,
    21,
    30,
    30,
    30,
    31,
    31,
    31,
    32,
    32,
    32,
    21,
    33,
    33,
    33,
    87,
    30,
    34,
    34,
    34,
    35,
    35,

    35,
    81,
    102,
    29,
    102,
    87,
    30,
    57,
    51,
    31,
    32,
    36,
    36,
    36,
    33,
    45,
    33,
    35,
    37,
    37,
    37,
    34,
    103,
    35,
    43,
    38,
    38,
    38,
    104,
    36,
    104,
    39,
    39,
    39,
    103,
    49,
    49,
    49,
    116,
    50,
    116,
    50,
    41,
    49,
    50,
    50,
    50,
    53,
    53,
    53,
    37,
    38,
    39,
    49,
    54,
    53,
    54,
    54,
    54,
    55,
    25,
    55,
    55,
    55,
    54,
    53,
    56,
    24,
    56,
    55,
    23,
    56,
    56,
    56,
    54,
    63,
    63,
    63,
    58,
    55,
    58,
    58,
    58,
    64,
    64,
    64,
    14,
    11,
    58,
    65,
    65,
    65,
    9,
    66,
    66,
    66,
    8,
    117,
    58,
    117,

    7,
    64,
    67,
    67,
    67,
    68,
    68,
    68,
    69,
    69,
    69,
    70,
    70,
    70,
    71,
    71,
    71,
    65,
    66,
    72,
    72,
    72,
    73,
    73,
    73,
    74,
    74,
    74,
    75,
    75,
    75,
    3,
    0,
    68,
    69,
    76,
    76,
    76,
    70,
    77,
    77,
    77,
    0,
    71,
    79,
    79,
    79,
    80,
    80,
    80,
    75,
    73,
    0,
    118,
    74,
    118,
    0,
    76,
    84,
    84,
    84,
    77,
    85,
    85,
    85,
    88,
    88,
    88,
    89,
    89,
    89,
    90,
    90,
    90,
    91,
    91,
    91,
    0,
    0,
    88,
    92,
    92,
    92,
    93,
    93,
    93,
    89,
    94,
    94,
    94,
    0,
    119,
    91,
    119,
    92,
    95,
    95,
    95,
    0,
    90,

    90,
    96,
    96,
    96,
    97,
    97,
    97,
    98,
    98,
    98,
    99,
    99,
    99,
    94,
    105,
    105,
    105,
    106,
    106,
    106,
    107,
    107,
    107,
    0,
    98,
    108,
    108,
    108,
    109,
    109,
    109,
    96,
    0,
    97,
    99,
    0,
    0,
    105,
    110,
    110,
    110,
    111,
    111,
    111,
    112,
    112,
    112,
    108,
    0,
    107,
    113,
    113,
    113,
    114,
    114,
    114,
    115,
    115,
    115,
    120,
    120,
    120,
    121,
    121,
    121,
    0,
    113,
    110,
    122,
    122,
    122,
    112,
    0,
    0,
    115,
    123,
    123,
    123,
    124,
    124,
    124,
    125,
    125,
    125,
    126,
    126,
    126,
    127,
    127,
    127,
    128,
    128,
    128,
    122,
    129,
    129,
    129,
    130,
    130,
    130,

    0,
    0,
    125,
    124,
    131,
    131,
    131,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    0,
    130,
    0,
    127,
    133,
    133,
    133,
    133,
    133,
    133,
    133,
    134,
    134,
    134,
    135,
    135,
    135,
    135,
    135,
    135,
    135,
    136,
    0,
    136,
    136,
    136,
    136,
    136,
    137,
    137,
    138,
    138,
    138,
    139,
    0,
    139,
    140,
    140,
    0,
    140,
    141,
    0,
    141,
    142,
    0,
    142,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,

    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132,
    132};

static const flex_int16_t yy_rule_linenum[58] = {0,
    39,
    44,
    45,
    49,
    50,
    51,
    52,
    53,
    54,
    55,
    56,
    57,
    58,
    59,
    60,
    61,
    62,
    64,
    66,
    67,
    68,
    69,
    70,
    71,
    72,
    73,
    74,
    75,
    76,
    77,
    78,
    79,
    80,
    81,
    82,
    83,
    84,
    85,
    87,
    92,
    105,
    111,
    117,
    122,
    130,
    140,
    150,
    160,
    170,
    183,
    196,
    209,
    210,
    211,
    212,
    213,
    214};

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "parser/lexer.l"
#line 2 "parser/lexer.l"
#include <stdexcept>
#include <string>
#include <memory>

#include <parser/yacc.hpp>
#include <parser/scanner.h>
#include <parser/location.hh>
#include <parser/driver.h>

using namespace Yacc;

static location loc;

#define YY_USER_ACTION \
    loc.step();        \
    loc.columns(yyleng);

#define yywrap() 1
#define RETT(x, y) return Parser::make_##x(y);

#define TAB_WIDTH 4

extern long long convertToInt(const char* str, const char end, bool& isLongLong);
extern float     convertToFloatDec(const char* str);
extern float     convertToFloatHex(const char* str);

int handleTab();
#line 695 "parser/lexer.cpp"
#line 696 "parser/lexer.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#include <unistd.h>
/* %endif */
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void*
#endif

/* %if-c-only Reentrant structure and macros (non-C++). */
/* %if-reentrant */
/* %if-c-only */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif End reentrant structures and macros. */
/* %if-bison-bridge */
/* %endif */
/* %not-for-header */
/* %ok-for-header */

/* %endif */

#ifndef yytext_ptr
static void yy_flex_strncpy(char*, const char*, int);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char*);
#endif

#ifndef YY_NO_INPUT
/* %if-c-only Standard (non-C++) definition */
/* %not-for-header */
/* %ok-for-header */

/* %endif */
#endif

/* %if-c-only */
/* %endif */

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define ECHO LexerOutput(yytext, yyleng)
/* %endif */
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf, result, max_size)                                                     \
    /* %% [5.0] fread()/read() definition of YY_INPUT goes here unless we're doing C++ \ */ \
                                                                                            \
    /* %if-c++-only C++ definition \ */                                                     \
    if ((int)(result = LexerInput((char*)buf, max_size)) < 0) YY_FATAL_ERROR("input in flex scanner failed");
/* %endif */

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
/* %if-c-only */
/* %endif */
/* %if-c++-only */
#define YY_FATAL_ERROR(msg) LexerError(msg)
/* %endif */
#endif

/* %if-tables-serialization structures and prototypes */
/* %not-for-header */
/* %ok-for-header */

/* %not-for-header */
/* %tables-yydmap generated elements */
/* %endif */
/* end tables serialization structures and prototypes */

/* %ok-for-header */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
/* %if-c-only Standard (non-C++) definition */
/* %endif */
/* %if-c++-only C++ definition */
#define YY_DECL int yyFlexLexer::yylex()
/* %endif */
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/ break;
#endif

/* %% [6.0] YY_RULE_SETUP definition goes here */
#define YY_RULE_SETUP YY_USER_ACTION

/* %not-for-header */
/** The main scanner function which does all the work.
 */
YY_DECL
{
    yy_state_type yy_current_state;
    char *        yy_cp, *yy_bp;
    int           yy_act;

    if (!(yy_init))
    {
        (yy_init) = 1;

#ifdef YY_USER_INIT
        YY_USER_INIT;
#endif

        if (!(yy_start)) (yy_start) = 1; /* first start state */

        if (!yyin) /* %if-c-only */
                   /* %endif */
                   /* %if-c++-only */
            yyin.rdbuf(std::cin.rdbuf());
        /* %endif */

        if (!yyout) /* %if-c-only */
                    /* %endif */
                    /* %if-c++-only */
            yyout.rdbuf(std::cout.rdbuf());
        /* %endif */

        if (!YY_CURRENT_BUFFER)
        {
            yyensure_buffer_stack();
            YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
        }

        yy_load_buffer_state();
    }

    {
/* %% [7.0] user's declarations go here */
#line 37 "parser/lexer.l"

#line 891 "parser/lexer.cpp"

        while (/*CONSTCOND*/ 1) /* loops until end-of-file is reached */
        {
            /* %% [8.0] yymore()-related code goes here */
            yy_cp = (yy_c_buf_p);

            /* Support of yytext. */
            *yy_cp = (yy_hold_char);

            /* yy_bp points to the position in yy_ch_buf of the start of
             * the current run.
             */
            yy_bp = yy_cp;

            /* %% [9.0] code to set up and find next match goes here */
            yy_current_state = (yy_start);
        yy_match:
            do {
                YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
                if (yy_accept[yy_current_state])
                {
                    (yy_last_accepting_state) = yy_current_state;
                    (yy_last_accepting_cpos)  = yy_cp;
                }
                while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
                {
                    yy_current_state = (int)yy_def[yy_current_state];
                    if (yy_current_state >= 133) yy_c = yy_meta[yy_c];
                }
                yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
                ++yy_cp;
            } while (yy_base[yy_current_state] != 461);

        yy_find_action:
            /* %% [10.0] code to find the action number goes here */
            yy_act = yy_accept[yy_current_state];
            if (yy_act == 0)
            { /* have to back up */
                yy_cp            = (yy_last_accepting_cpos);
                yy_current_state = (yy_last_accepting_state);
                yy_act           = yy_accept[yy_current_state];
            }

            YY_DO_BEFORE_ACTION;

            /* %% [11.0] code for yylineno update goes here */

        do_action: /* This label is used only to access EOF actions. */

            /* %% [12.0] debug code goes here */
            if (yy_flex_debug)
            {
                if (yy_act == 0)
                    std::cerr << "--scanner backing up\n";
                else if (yy_act < 58)
                    std::cerr << "--accepting rule at line " << yy_rule_linenum[yy_act] << "(\"" << yytext << "\")\n";
                else if (yy_act == 58)
                    std::cerr << "--accepting default rule (\"" << yytext << "\")\n";
                else if (yy_act == 59)
                    std::cerr << "--(end of buffer or a NUL)\n";
                else
                    std::cerr << "--EOF (start condition " << YY_START << ")\n";
            }

            switch (yy_act)
            {           /* beginning of action switch */
                        /* %% [13.0] actions go here */
                case 0: /* must back up */
                    /* undo the effects of YY_DO_BEFORE_ACTION */
                    *yy_cp           = (yy_hold_char);
                    yy_cp            = (yy_last_accepting_cpos);
                    yy_current_state = (yy_last_accepting_state);
                    goto yy_find_action;

                case 1:
                    /* rule 1 can match eol */
                    YY_RULE_SETUP
#line 39 "parser/lexer.l"
                    {
                        loc.lines(yyleng);
                        loc.step();
                    }
                    YY_BREAK
                case 2: YY_RULE_SETUP
#line 44 "parser/lexer.l"
                    { /* empty */
                    }
                    YY_BREAK
                case 3: YY_RULE_SETUP
#line 45 "parser/lexer.l"
                    {
                        loc.columns(handleTab());
                    }
                    YY_BREAK
                case 4:
                YY_RULE_SETUP
#line 49 "parser/lexer.l"
                    {RETT(INT, loc)} YY_BREAK case 5:
                YY_RULE_SETUP
#line 50 "parser/lexer.l"
                    {RETT(FLOAT, loc)} YY_BREAK case 6:
                YY_RULE_SETUP
#line 51 "parser/lexer.l"
                    {RETT(VOID, loc)} YY_BREAK case 7:
                YY_RULE_SETUP
#line 52 "parser/lexer.l"
                    {RETT(IF, loc)} YY_BREAK case 8:
                YY_RULE_SETUP
#line 53 "parser/lexer.l"
                    {RETT(ELSE, loc)} YY_BREAK case 9:
                YY_RULE_SETUP
#line 54 "parser/lexer.l"
                    {RETT(FOR, loc)} YY_BREAK case 10:
                YY_RULE_SETUP
#line 55 "parser/lexer.l"
                    {RETT(WHILE, loc)} YY_BREAK case 11:
                YY_RULE_SETUP
#line 56 "parser/lexer.l"
                    {RETT(CONTINUE, loc)} YY_BREAK case 12:
                YY_RULE_SETUP
#line 57 "parser/lexer.l"
                    {RETT(BREAK, loc)} YY_BREAK case 13:
                YY_RULE_SETUP
#line 58 "parser/lexer.l"
                    {RETT(SWITCH, loc)} YY_BREAK case 14:
                YY_RULE_SETUP
#line 59 "parser/lexer.l"
                    {RETT(CASE, loc)} YY_BREAK case 15:
                YY_RULE_SETUP
#line 60 "parser/lexer.l"
                    {RETT(GOTO, loc)} YY_BREAK case 16:
                YY_RULE_SETUP
#line 61 "parser/lexer.l"
                    {RETT(DO, loc)} YY_BREAK case 17:
                YY_RULE_SETUP
#line 62 "parser/lexer.l"
                    {RETT(RETURN, loc)} YY_BREAK case 18:
                YY_RULE_SETUP
#line 64 "parser/lexer.l"
                    {RETT(CONST, loc)} YY_BREAK case 19:
                YY_RULE_SETUP
#line 66 "parser/lexer.l"
                    {RETT(SEMICOLON, loc)} YY_BREAK case 20:
                YY_RULE_SETUP
#line 67 "parser/lexer.l"
                    {RETT(COMMA, loc)} YY_BREAK case 21:
                YY_RULE_SETUP
#line 68 "parser/lexer.l"
                    {RETT(ASSIGN, loc)} YY_BREAK case 22:
                YY_RULE_SETUP
#line 69 "parser/lexer.l"
                    {RETT(NOT, loc)} YY_BREAK case 23:
                YY_RULE_SETUP
#line 70 "parser/lexer.l"
                    {RETT(BITOR, loc)} YY_BREAK case 24:
                YY_RULE_SETUP
#line 71 "parser/lexer.l"
                    {RETT(BITAND, loc)} YY_BREAK case 25:
                YY_RULE_SETUP
#line 72 "parser/lexer.l"
                    {RETT(GT, loc)} YY_BREAK case 26:
                YY_RULE_SETUP
#line 73 "parser/lexer.l"
                    {RETT(LT, loc)} YY_BREAK case 27:
                YY_RULE_SETUP
#line 74 "parser/lexer.l"
                    {RETT(PLUS, loc)} YY_BREAK case 28:
                YY_RULE_SETUP
#line 75 "parser/lexer.l"
                    {RETT(MINUS, loc)} YY_BREAK case 29:
                YY_RULE_SETUP
#line 76 "parser/lexer.l"
                    {RETT(STAR, loc)} YY_BREAK case 30:
                YY_RULE_SETUP
#line 77 "parser/lexer.l"
                    {RETT(SLASH, loc)} YY_BREAK case 31:
                YY_RULE_SETUP
#line 78 "parser/lexer.l"
                    {RETT(MOD, loc)} YY_BREAK case 32:
                YY_RULE_SETUP
#line 79 "parser/lexer.l"
                    {RETT(DOT, loc)} YY_BREAK case 33:
                YY_RULE_SETUP
#line 80 "parser/lexer.l"
                    {RETT(GE, loc)} YY_BREAK case 34:
                YY_RULE_SETUP
#line 81 "parser/lexer.l"
                    {RETT(LE, loc)} YY_BREAK case 35:
                YY_RULE_SETUP
#line 82 "parser/lexer.l"
                    {RETT(EQ, loc)} YY_BREAK case 36:
                YY_RULE_SETUP
#line 83 "parser/lexer.l"
                    {RETT(NEQ, loc)} YY_BREAK case 37:
                YY_RULE_SETUP
#line 84 "parser/lexer.l"
                    {RETT(AND, loc)} YY_BREAK case 38:
                YY_RULE_SETUP
#line 85 "parser/lexer.l"
                    {RETT(OR, loc)} YY_BREAK case 39:
                    YY_RULE_SETUP
#line 87 "parser/lexer.l"
                    {
                        auto str = std::make_shared<std::string>(yytext);
                        // return Parser::make_SLASH_COMMENT(str, loc);
                    }
                    YY_BREAK
                case 40:
                    /* rule 40 can match eol */
                    YY_RULE_SETUP
#line 92 "parser/lexer.l"
                    {
                        int cnt = 0;
                        for (int i = 0; yytext[i] != '\0'; ++i)
                        {
                            if (yytext[i] == '\n')
                            {
                                ++cnt;
                                yytext[i] = ' ';
                            }
                        }
                        for (int i = 0; i < cnt; ++i) loc.lines();
                        auto str = std::make_shared<std::string>(yytext);
                        // return Parser::make_SLASH_COMMENT(str, loc);
                    }
                    YY_BREAK
                case 41: YY_RULE_SETUP
#line 105 "parser/lexer.l"
                    {
                        _driver.reportError(loc, yytext);
                        auto str = std::make_shared<std::string>(yytext);
                        return Parser::make_ERR_TOKEN(str, loc);
                    }
                    YY_BREAK
                case 42: YY_RULE_SETUP
#line 111 "parser/lexer.l"
                    {
                        _driver.reportError(loc, yytext);
                        auto str = std::make_shared<std::string>(yytext);
                        return Parser::make_ERR_TOKEN(str, loc);
                    }
                    YY_BREAK
                case 43: YY_RULE_SETUP
#line 117 "parser/lexer.l"
                    {
                        auto str = std::make_shared<std::string>(yytext);
                        return Parser::make_IDENT(str, loc);
                    }
                    YY_BREAK
                case 44:
                    /* rule 44 can match eol */
                    YY_RULE_SETUP
#line 122 "parser/lexer.l"
                    {
                        std::string str(yytext);
                        if (!str.empty()) str = str.substr(1, str.size() - 2);
                        auto shared_str = std::make_shared<std::string>(str);
                        return Parser::make_STR_CONST(shared_str, loc);
                    }
                    YY_BREAK
                case 45: YY_RULE_SETUP
#line 130 "parser/lexer.l"
                    {
                        try
                        {
                            return Parser::make_FLOAT_CONST(convertToFloatDec(yytext), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing float: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 46: YY_RULE_SETUP
#line 140 "parser/lexer.l"
                    {
                        try
                        {
                            return Parser::make_FLOAT_CONST(convertToFloatDec(yytext), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing float: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 47: YY_RULE_SETUP
#line 150 "parser/lexer.l"
                    {
                        try
                        {
                            return Parser::make_FLOAT_CONST(convertToFloatHex(yytext), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing hexadecimal float: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 48: YY_RULE_SETUP
#line 160 "parser/lexer.l"
                    {
                        try
                        {
                            return Parser::make_FLOAT_CONST(convertToFloatHex(yytext), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing hexadecimal float: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 49: YY_RULE_SETUP
#line 170 "parser/lexer.l"
                    {
                        try
                        {
                            bool      isLL   = false;
                            long long result = convertToInt(yytext, '\0', isLL);
                            if (isLL) return Parser::make_LL_CONST(result, loc);
                            return Parser::make_INT_CONST(static_cast<int>(result), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing hexadecimal int: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 50: YY_RULE_SETUP
#line 183 "parser/lexer.l"
                    {
                        try
                        {
                            bool      isLL   = false;
                            long long result = convertToInt(yytext, '\0', isLL);
                            if (isLL) return Parser::make_LL_CONST(result, loc);
                            return Parser::make_INT_CONST(static_cast<int>(result), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing hexadecimal int: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 51: YY_RULE_SETUP
#line 196 "parser/lexer.l"
                    {
                        try
                        {
                            bool      isLL   = false;
                            long long result = convertToInt(yytext, '\0', isLL);
                            if (isLL) return Parser::make_LL_CONST(result, loc);
                            return Parser::make_INT_CONST(static_cast<int>(result), loc);
                        } catch (const std::exception& e)
                        {
                            _driver.reportError(loc, std::string("Error parsing hexadecimal int: ") + e.what());
                            auto str = std::make_shared<std::string>(yytext);
                            return Parser::make_ERR_TOKEN(str, loc);
                        }
                    }
                    YY_BREAK
                case 52:
                YY_RULE_SETUP
#line 209 "parser/lexer.l"
                    {RETT(LPAREN, loc)} YY_BREAK case 53:
                YY_RULE_SETUP
#line 210 "parser/lexer.l"
                    {RETT(RPAREN, loc)} YY_BREAK case 54:
                YY_RULE_SETUP
#line 211 "parser/lexer.l"
                    {RETT(LBRACKET, loc)} YY_BREAK case 55:
                YY_RULE_SETUP
#line 212 "parser/lexer.l"
                    {RETT(RBRACKET, loc)} YY_BREAK case 56:
                YY_RULE_SETUP
#line 213 "parser/lexer.l"
                    {RETT(LBRACE, loc)} YY_BREAK case 57:
                YY_RULE_SETUP
#line 214 "parser/lexer.l"
                    {RETT(RBRACE, loc)} YY_BREAK case YY_STATE_EOF(INITIAL):
#line 216 "parser/lexer.l"
                {
                    RETT(END, loc);
                }
                    YY_BREAK
                case 58: YY_RULE_SETUP
#line 218 "parser/lexer.l"
                    ECHO;
                    YY_BREAK
#line 1367 "parser/lexer.cpp"

                case YY_END_OF_BUFFER:
                {
                    /* Amount of text matched not including the EOB char. */
                    int yy_amount_of_matched_text = (int)(yy_cp - (yytext_ptr)) - 1;

                    /* Undo the effects of YY_DO_BEFORE_ACTION. */
                    *yy_cp = (yy_hold_char);
                    YY_RESTORE_YY_MORE_OFFSET

                    if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW)
                    {
                        /* We're scanning a new file or input source.  It's
                         * possible that this happened because the user
                         * just pointed yyin at a new source and called
                         * yylex().  If so, then we have to assure
                         * consistency between YY_CURRENT_BUFFER and our
                         * globals.  Here is the right place to do so, because
                         * this is the first action (other than possibly a
                         * back-up) that will match for the new input source.
                         */
                        (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
                        /* %if-c-only */
                        /* %endif */
                        /* %if-c++-only */
                        YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin.rdbuf();
                        /* %endif */
                        YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
                    }

                    /* Note that here we test for yy_c_buf_p "<=" to the position
                     * of the first EOB in the buffer, since yy_c_buf_p will
                     * already have been incremented past the NUL character
                     * (since all states make transitions on EOB to the
                     * end-of-buffer state).  Contrast this with the test
                     * in input().
                     */
                    if ((yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)])
                    { /* This was really a NUL. */
                        yy_state_type yy_next_state;

                        (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

                        yy_current_state = yy_get_previous_state();

                        /* Okay, we're now positioned to make the NUL
                         * transition.  We couldn't have
                         * yy_get_previous_state() go ahead and do it
                         * for us because it doesn't know how to deal
                         * with the possibility of jamming (and we don't
                         * want to build jamming into it because then it
                         * will run more slowly).
                         */

                        yy_next_state = yy_try_NUL_trans(yy_current_state);

                        yy_bp = (yytext_ptr) + YY_MORE_ADJ;

                        if (yy_next_state)
                        {
                            /* Consume the NUL. */
                            yy_cp            = ++(yy_c_buf_p);
                            yy_current_state = yy_next_state;
                            goto yy_match;
                        }

                        else
                        {
                            /* %% [14.0] code to do back-up for compressed tables and set up yy_cp goes here */
                            yy_cp = (yy_c_buf_p);
                            goto yy_find_action;
                        }
                    }

                    else
                        switch (yy_get_next_buffer())
                        {
                            case EOB_ACT_END_OF_FILE:
                            {
                                (yy_did_buffer_switch_on_eof) = 0;

                                if (yywrap())
                                {
                                    /* Note: because we've taken care in
                                     * yy_get_next_buffer() to have set up
                                     * yytext, we can now set up
                                     * yy_c_buf_p so that if some total
                                     * hoser (like flex itself) wants to
                                     * call the scanner after we return the
                                     * YY_NULL, it'll still work - another
                                     * YY_NULL will get returned.
                                     */
                                    (yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

                                    yy_act = YY_STATE_EOF(YY_START);
                                    goto do_action;
                                }

                                else
                                {
                                    if (!(yy_did_buffer_switch_on_eof)) YY_NEW_FILE;
                                }
                                break;
                            }

                            case EOB_ACT_CONTINUE_SCAN:
                                (yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

                                yy_current_state = yy_get_previous_state();

                                yy_cp = (yy_c_buf_p);
                                yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                                goto yy_match;

                            case EOB_ACT_LAST_MATCH:
                                (yy_c_buf_p) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

                                yy_current_state = yy_get_previous_state();

                                yy_cp = (yy_c_buf_p);
                                yy_bp = (yytext_ptr) + YY_MORE_ADJ;
                                goto yy_find_action;
                        }
                    break;
                }

                default: YY_FATAL_ERROR("fatal flex scanner internal error--no action found");
            } /* end of action switch */
        } /* end of scanning one token */
    } /* end of user's declarations */
} /* end of yylex */
/* %ok-for-header */

/* %if-c++-only */
/* %not-for-header */
/* The contents of this function are C++ specific, so the () macro is not used.
 * This constructor simply maintains backward compatibility.
 * DEPRECATED
 */
yyFlexLexer::yyFlexLexer(std::istream* arg_yyin, std::ostream* arg_yyout)
    : yyin(arg_yyin ? arg_yyin->rdbuf() : std::cin.rdbuf()), yyout(arg_yyout ? arg_yyout->rdbuf() : std::cout.rdbuf())
{
    ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer(std::istream& arg_yyin, std::ostream& arg_yyout)
    : yyin(arg_yyin.rdbuf()), yyout(arg_yyout.rdbuf())
{
    ctor_common();
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::ctor_common()
{
    yy_c_buf_p    = 0;
    yy_init       = 0;
    yy_start      = 0;
    yy_flex_debug = 0;
    yylineno      = 1;  // this will only get updated if %option yylineno

    yy_did_buffer_switch_on_eof = 0;

    yy_looking_for_trail_begin = 0;
    yy_more_flag               = 0;
    yy_more_len                = 0;
    yy_more_offset = yy_prev_more_offset = 0;

    yy_start_stack_ptr = yy_start_stack_depth = 0;
    yy_start_stack                            = NULL;

    yy_buffer_stack     = NULL;
    yy_buffer_stack_top = 0;
    yy_buffer_stack_max = 0;

    yy_state_buf = 0;
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
    delete[] yy_state_buf;
    yyfree(yy_start_stack);
    yy_delete_buffer(YY_CURRENT_BUFFER);
    yyfree(yy_buffer_stack);
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams(std::istream& new_in, std::ostream& new_out)
{
    // was if( new_in )
    yy_delete_buffer(YY_CURRENT_BUFFER);
    yy_switch_to_buffer(yy_create_buffer(new_in, YY_BUF_SIZE));

    // was if( new_out )
    yyout.rdbuf(new_out.rdbuf());
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams(std::istream* new_in, std::ostream* new_out)
{
    if (!new_in) { new_in = &yyin; }

    if (!new_out) { new_out = &yyout; }

    switch_streams(*new_in, *new_out);
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput(char* buf, int /* max_size */)
#else
int yyFlexLexer::LexerInput(char* buf, int max_size)
#endif
{
    if (yyin.eof() || yyin.fail()) return 0;

#ifdef YY_INTERACTIVE
    yyin.get(buf[0]);

    if (yyin.eof()) return 0;

    if (yyin.bad()) return -1;

    return 1;

#else
    (void)yyin.read(buf, max_size);

    if (yyin.bad())
        return -1;
    else
        return yyin.gcount();
#endif
}

void yyFlexLexer::LexerOutput(const char* buf, int size) { (void)yyout.write(buf, size); }
/* %ok-for-header */

/* %endif */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_get_next_buffer()
/* %endif */
{
    char* dest   = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
    char* source = (yytext_ptr);
    int   number_to_move, i;
    int   ret_val;

    if ((yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1])
        YY_FATAL_ERROR("fatal flex scanner internal error--end of buffer missed");

    if (YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0)
    { /* Don't try to fill the buffer, so this is an EOF. */
        if ((yy_c_buf_p) - (yytext_ptr)-YY_MORE_ADJ == 1)
        {
            /* We matched a single character, the EOB, so
             * treat this as a final EOF.
             */
            return EOB_ACT_END_OF_FILE;
        }

        else
        {
            /* We matched some text prior to the EOB, first
             * process it.
             */
            return EOB_ACT_LAST_MATCH;
        }
    }

    /* Try to read more data. */

    /* First move last chars to start of buffer. */
    number_to_move = (int)((yy_c_buf_p) - (yytext_ptr)-1);

    for (i = 0; i < number_to_move; ++i) *(dest++) = *(source++);

    if (YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING)
        /* don't do the read, it's not guaranteed to return an EOF,
         * just force an EOF
         */
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

    else
    {
        int num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

        while (num_to_read <= 0)
        { /* Not enough room in the buffer - grow it. */

            /* just a shorter name for the current buffer */
            YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

            int yy_c_buf_p_offset = (int)((yy_c_buf_p)-b->yy_ch_buf);

            if (b->yy_is_our_buffer)
            {
                int new_size = b->yy_buf_size * 2;

                if (new_size <= 0)
                    b->yy_buf_size += b->yy_buf_size / 8;
                else
                    b->yy_buf_size *= 2;

                b->yy_ch_buf = (char*)
                    /* Include room in for 2 EOB chars. */
                    yyrealloc((void*)b->yy_ch_buf, (yy_size_t)(b->yy_buf_size + 2));
            }
            else
                /* Can't grow it, we don't own it. */
                b->yy_ch_buf = NULL;

            if (!b->yy_ch_buf) YY_FATAL_ERROR("fatal error - scanner input buffer overflow");

            (yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

            num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;
        }

        if (num_to_read > YY_READ_BUF_SIZE) num_to_read = YY_READ_BUF_SIZE;

        /* Read in more data. */
        YY_INPUT((&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]), (yy_n_chars), num_to_read);

        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    if ((yy_n_chars) == 0)
    {
        if (number_to_move == YY_MORE_ADJ)
        {
            ret_val = EOB_ACT_END_OF_FILE;
            yyrestart(yyin);
        }

        else
        {
            ret_val                                    = EOB_ACT_LAST_MATCH;
            YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_EOF_PENDING;
        }
    }

    else
        ret_val = EOB_ACT_CONTINUE_SCAN;

    if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size)
    {
        /* Extend the array by 50%, plus the number we really need. */
        int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
        YY_CURRENT_BUFFER_LVALUE->yy_ch_buf =
            (char*)yyrealloc((void*)YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t)new_size);
        if (!YY_CURRENT_BUFFER_LVALUE->yy_ch_buf) YY_FATAL_ERROR("out of dynamic memory in yy_get_next_buffer()");
        /* "- 2" to take care of EOB's */
        YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int)(new_size - 2);
    }

    (yy_n_chars) += number_to_move;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)]     = YY_END_OF_BUFFER_CHAR;
    YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

    (yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

    return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

/* %if-c-only */
/* %not-for-header */
/* %endif */
/* %if-c++-only */
yy_state_type yyFlexLexer::yy_get_previous_state()
/* %endif */
{
    yy_state_type yy_current_state;
    char*         yy_cp;

    /* %% [15.0] code to get the start state into yy_current_state goes here */
    yy_current_state = (yy_start);

    for (yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp)
    {
        /* %% [16.0] code to find the next state goes here */
        YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
        if (yy_accept[yy_current_state])
        {
            (yy_last_accepting_state) = yy_current_state;
            (yy_last_accepting_cpos)  = yy_cp;
        }
        while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
        {
            yy_current_state = (int)yy_def[yy_current_state];
            if (yy_current_state >= 133) yy_c = yy_meta[yy_c];
        }
        yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    }

    return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
yy_state_type yyFlexLexer::yy_try_NUL_trans(yy_state_type yy_current_state)
/* %endif */
{
    int yy_is_jam;
    /* %% [17.0] code to find the next state, and perhaps do backing up, goes here */
    char* yy_cp = (yy_c_buf_p);

    YY_CHAR yy_c = 1;
    if (yy_accept[yy_current_state])
    {
        (yy_last_accepting_state) = yy_current_state;
        (yy_last_accepting_cpos)  = yy_cp;
    }
    while (yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state)
    {
        yy_current_state = (int)yy_def[yy_current_state];
        if (yy_current_state >= 133) yy_c = yy_meta[yy_c];
    }
    yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
    yy_is_jam        = (yy_current_state == 132);

    return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyunput(int c, char* yy_bp)
/* %endif */
{
    char* yy_cp;

    yy_cp = (yy_c_buf_p);

    /* undo effects of setting up yytext */
    *yy_cp = (yy_hold_char);

    if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2)
    { /* need to shift things up to make room */
        /* +2 for EOB chars. */
        int   number_to_move = (yy_n_chars) + 2;
        char* dest           = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
        char* source         = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

        while (source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf) *--dest = *--source;

        yy_cp += (int)(dest - source);
        yy_bp += (int)(dest - source);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = (int)YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

        if (yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2) YY_FATAL_ERROR("flex scanner push-back overflow");
    }

    *--yy_cp = (char)c;

    /* %% [18.0] update yylineno here */

    (yytext_ptr)   = yy_bp;
    (yy_hold_char) = *yy_cp;
    (yy_c_buf_p)   = yy_cp;
}
/* %if-c-only */
/* %endif */
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yyinput()
/* %endif */
{
    int c;

    *(yy_c_buf_p) = (yy_hold_char);

    if (*(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR)
    {
        /* yy_c_buf_p now points to the character we want to return.
         * If this occurs *before* the EOB characters, then it's a
         * valid NUL; if not, then we've hit the end of the buffer.
         */
        if ((yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)]) /* This was really a NUL. */
            *(yy_c_buf_p) = '\0';

        else
        { /* need more input */
            int offset = (int)((yy_c_buf_p) - (yytext_ptr));
            ++(yy_c_buf_p);

            switch (yy_get_next_buffer())
            {
                case EOB_ACT_LAST_MATCH:
                    /* This happens because yy_g_n_b()
                     * sees that we've accumulated a
                     * token and flags that we need to
                     * try matching the token before
                     * proceeding.  But for input(),
                     * there's no matching to consider.
                     * So convert the EOB_ACT_LAST_MATCH
                     * to EOB_ACT_END_OF_FILE.
                     */

                    /* Reset buffer status. */
                    yyrestart(yyin);

                    /*FALLTHROUGH*/

                case EOB_ACT_END_OF_FILE:
                {
                    if (yywrap()) return 0;

                    if (!(yy_did_buffer_switch_on_eof)) YY_NEW_FILE;
#ifdef __cplusplus
                    return yyinput();
#else
                    return input();
#endif
                }

                case EOB_ACT_CONTINUE_SCAN: (yy_c_buf_p) = (yytext_ptr) + offset; break;
            }
        }
    }

    c              = *(unsigned char*)(yy_c_buf_p); /* cast for 8-bit char's */
    *(yy_c_buf_p)  = '\0';                          /* preserve yytext */
    (yy_hold_char) = *++(yy_c_buf_p);

    /* %% [19.0] update BOL and yylineno */

    return c;
}
/* %if-c-only */
/* %endif */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyrestart(std::istream& input_file)
/* %endif */
{

    if (!YY_CURRENT_BUFFER)
    {
        yyensure_buffer_stack();
        YY_CURRENT_BUFFER_LVALUE = yy_create_buffer(yyin, YY_BUF_SIZE);
    }

    yy_init_buffer(YY_CURRENT_BUFFER, input_file);
    yy_load_buffer_state();
}

/* %if-c++-only */
/** Delegate to the new version that takes an istream reference.
 * @param input_file A readable stream.
 *
 * @note This function does not reset the start condition to @c INITIAL .
 */
void yyFlexLexer::yyrestart(std::istream* input_file)
{
    if (!input_file) { input_file = &yyin; }
    yyrestart(*input_file);
}
/* %endif */

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 *
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_switch_to_buffer(YY_BUFFER_STATE new_buffer)
/* %endif */
{

    /* TODO. We should be able to replace this entire function body
     * with
     *		yypop_buffer_state();
     *		yypush_buffer_state(new_buffer);
     */
    yyensure_buffer_stack();
    if (YY_CURRENT_BUFFER == new_buffer) return;

    if (YY_CURRENT_BUFFER)
    {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p)                        = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    YY_CURRENT_BUFFER_LVALUE = new_buffer;
    yy_load_buffer_state();

    /* We don't actually know whether we did this switch during
     * EOF (yywrap()) processing, but the only time this flag
     * is looked at is after yywrap() is called, so it's safe
     * to go ahead and always set it.
     */
    (yy_did_buffer_switch_on_eof) = 1;
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_load_buffer_state()
/* %endif */
{
    (yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
    (yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
    /* %if-c-only */
    /* %endif */
    /* %if-c++-only */
    yyin.rdbuf(YY_CURRENT_BUFFER_LVALUE->yy_input_file);
    /* %endif */
    (yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
YY_BUFFER_STATE yyFlexLexer::yy_create_buffer(std::istream& file, int size)
/* %endif */
{
    YY_BUFFER_STATE b;

    b = (YY_BUFFER_STATE)yyalloc(sizeof(struct yy_buffer_state));
    if (!b) YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_buf_size = size;

    /* yy_ch_buf has to be 2 characters longer than the size given because
     * we need to put in 2 end-of-buffer characters.
     */
    b->yy_ch_buf = (char*)yyalloc((yy_size_t)(b->yy_buf_size + 2));
    if (!b->yy_ch_buf) YY_FATAL_ERROR("out of dynamic memory in yy_create_buffer()");

    b->yy_is_our_buffer = 1;

    yy_init_buffer(b, file);

    return b;
}

/* %if-c++-only */
/** Delegate creation of buffers to the new version that takes an istream reference.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 *
 * @return the allocated buffer state.
 */
YY_BUFFER_STATE yyFlexLexer::yy_create_buffer(std::istream* file, int size) { return yy_create_buffer(*file, size); }
/* %endif */

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 *
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_delete_buffer(YY_BUFFER_STATE b)
/* %endif */
{

    if (!b) return;

    if (b == YY_CURRENT_BUFFER) /* Not sure if we should pop here. */
        YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE)0;

    if (b->yy_is_our_buffer) yyfree((void*)b->yy_ch_buf);

    yyfree((void*)b);
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_init_buffer(YY_BUFFER_STATE b, std::istream& file)
/* %endif */

{
    int oerrno = errno;

    yy_flush_buffer(b);

    /* %if-c-only */
    /* %endif */
    /* %if-c++-only */
    b->yy_input_file = file.rdbuf();
    /* %endif */
    b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER)
    {
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

    /* %if-c-only */
    /* %endif */
    /* %if-c++-only */
    b->yy_is_interactive = 0;
    /* %endif */
    errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 *
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_flush_buffer(YY_BUFFER_STATE b)
/* %endif */
{
    if (!b) return;

    b->yy_n_chars = 0;

    /* We always need two end-of-buffer characters.  The first causes
     * a transition to the end-of-buffer state.  The second causes
     * a jam in that state.
     */
    b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
    b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

    b->yy_buf_pos = &b->yy_ch_buf[0];

    b->yy_at_bol        = 1;
    b->yy_buffer_status = YY_BUFFER_NEW;

    if (b == YY_CURRENT_BUFFER) yy_load_buffer_state();
}

/* %if-c-or-c++ */
/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypush_buffer_state(YY_BUFFER_STATE new_buffer)
/* %endif */
{
    if (new_buffer == NULL) return;

    yyensure_buffer_stack();

    /* This block is copied from yy_switch_to_buffer. */
    if (YY_CURRENT_BUFFER)
    {
        /* Flush out information for old buffer. */
        *(yy_c_buf_p)                        = (yy_hold_char);
        YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
        YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
    }

    /* Only push if top exists. Otherwise, replace top. */
    if (YY_CURRENT_BUFFER) (yy_buffer_stack_top)++;
    YY_CURRENT_BUFFER_LVALUE = new_buffer;

    /* copied from yy_switch_to_buffer. */
    yy_load_buffer_state();
    (yy_did_buffer_switch_on_eof) = 1;
}
/* %endif */

/* %if-c-or-c++ */
/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yypop_buffer_state(void)
/* %endif */
{
    if (!YY_CURRENT_BUFFER) return;

    yy_delete_buffer(YY_CURRENT_BUFFER);
    YY_CURRENT_BUFFER_LVALUE = NULL;
    if ((yy_buffer_stack_top) > 0) --(yy_buffer_stack_top);

    if (YY_CURRENT_BUFFER)
    {
        yy_load_buffer_state();
        (yy_did_buffer_switch_on_eof) = 1;
    }
}
/* %endif */

/* %if-c-or-c++ */
/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yyensure_buffer_stack(void)
/* %endif */
{
    yy_size_t num_to_alloc;

    if (!(yy_buffer_stack))
    {

        /* First allocation is just for 2 elements, since we don't know if this
         * scanner will even need a stack. We use 2 instead of 1 to avoid an
         * immediate realloc on the next call.
         */
        num_to_alloc      = 1; /* After all that talk, this was set to 1 anyways... */
        (yy_buffer_stack) = (struct yy_buffer_state**)yyalloc(num_to_alloc * sizeof(struct yy_buffer_state*));
        if (!(yy_buffer_stack)) YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

        memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

        (yy_buffer_stack_max) = num_to_alloc;
        (yy_buffer_stack_top) = 0;
        return;
    }

    if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1)
    {

        /* Increase the buffer to prepare for a possible push. */
        yy_size_t grow_size = 8 /* arbitrary grow size */;

        num_to_alloc = (yy_buffer_stack_max) + grow_size;
        (yy_buffer_stack) =
            (struct yy_buffer_state**)yyrealloc((yy_buffer_stack), num_to_alloc * sizeof(struct yy_buffer_state*));
        if (!(yy_buffer_stack)) YY_FATAL_ERROR("out of dynamic memory in yyensure_buffer_stack()");

        /* zero only the new slots.*/
        memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
        (yy_buffer_stack_max) = num_to_alloc;
    }
}
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_push_state(int _new_state)
/* %endif */
{
    if ((yy_start_stack_ptr) >= (yy_start_stack_depth))
    {
        yy_size_t new_size;

        (yy_start_stack_depth) += YY_START_STACK_INCR;
        new_size = (yy_size_t)(yy_start_stack_depth) * sizeof(int);

        if (!(yy_start_stack))
            (yy_start_stack) = (int*)yyalloc(new_size);

        else
            (yy_start_stack) = (int*)yyrealloc((void*)(yy_start_stack), new_size);

        if (!(yy_start_stack)) YY_FATAL_ERROR("out of memory expanding start-condition stack");
    }

    (yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

    BEGIN(_new_state);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::yy_pop_state()
/* %endif */
{
    if (--(yy_start_stack_ptr) < 0) YY_FATAL_ERROR("start-condition stack underflow");

    BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

/* %if-c-only */
/* %endif */
/* %if-c++-only */
int yyFlexLexer::yy_top_state()
/* %endif */
{
    return (yy_start_stack)[(yy_start_stack_ptr)-1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

/* %if-c-only */
/* %endif */
/* %if-c++-only */
void yyFlexLexer::LexerError(const char* msg)
{
    std::cerr << msg << std::endl;
    exit(YY_EXIT_FAILURE);
}
/* %endif */

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n)                                   \
    do {                                            \
        /* Undo effects of setting up yytext. */    \
        int yyless_macro_arg = (n);                 \
        YY_LESS_LINENO(yyless_macro_arg);           \
        yytext[yyleng] = (yy_hold_char);            \
        (yy_c_buf_p)   = yytext + yyless_macro_arg; \
        (yy_hold_char) = *(yy_c_buf_p);             \
        *(yy_c_buf_p)  = '\0';                      \
        yyleng         = yyless_macro_arg;          \
    } while (0)

/* Accessor  methods (get/set functions) to struct members. */

/* %if-c-only */
/* %if-reentrant */
/* %endif */
/* %if-reentrant */
/* %endif */
/* %endif */

/* %if-reentrant */
/* %if-bison-bridge */
/* %endif */
/* %endif if-c-only */

/* %if-c-only */
/* %endif */

/* %if-c-only SNIP! this currently causes conflicts with the c++ scanner */
/* %if-reentrant */
/* %endif */
/* %endif */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy(char* s1, const char* s2, int n)
{

    int i;
    for (i = 0; i < n; ++i) s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen(const char* s)
{
    int n;
    for (n = 0; s[n]; ++n);

    return n;
}
#endif

void* yyalloc(yy_size_t size) { return malloc(size); }

void* yyrealloc(void* ptr, yy_size_t size)
{

    /* The cast to (char *) in the following accommodates both
     * implementations that use char* generic pointers, and those
     * that use void* generic pointers.  It works with the latter
     * because both ANSI C and C++ allow castless assignment from
     * any pointer type to void*, and deal with argument conversions
     * as though doing an assignment.
     */
    return realloc(ptr, size);
}

void yyfree(void* ptr) { free((char*)ptr); /* see yyrealloc() for (char *) cast */ }

/* %if-tables-serialization definitions */
/* %define-yytables   The name for this specific scanner's tables. */
#define YYTABLES_NAME "yytables"
/* %endif */

/* %ok-for-header */

#line 218 "parser/lexer.l"

int handleTab()
{
    int& c = loc.begin.column;
    return TAB_WIDTH - ((c - 1) % TAB_WIDTH) - 1;
}
